# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#ç«™ç‚¹åŸºç¡€é…ç½®
title: DianaCody
subTitle: Thinking of code...
description: DianaCody's blog
url: http://dianacody.github.io
feed: /atom.xml

#èœå•é…ç½®
nav:
  - text: é¦–é¡µ
    url: /index.html
  - text: æ–‡ç« å½’æ¡£
    url: /archives.html
  - text: ä½œå“
    url: /works.html
  - text: è”ç³»æˆ?    url: http://dianacody.github.io/contact.html
  - text: åšå®¢æºä»£ç ?    url: https://github.com/dianacody/dianacody.github.com

#theme config
themes: /themes/violet

#é…ç½®ä½ å–œæ¬¢çš„é¡¶éƒ¨èƒŒæ™¯å›¾ç‰‡
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#å…³æ³¨æˆ?follow:
  - class: fa-google-plus
    url: http://dianacody.github.io
  - class: fa-facebook
    url: http://dianacody.github.io
  - class: fa-github
    url: http://github.com/dianacody
  - class: fa-weibo
    url: http://weibo.com/
  - class: fa-renren
    url: http://dianacody.github.io
  - class: fa-pinterest
    url: http://dianacody.github.io
  - class: fa-twitter
    url: http://dianacody.github.io
  - class: fa-rss
    url: http://dianacody.github.io

#ä½œè€…ä¿¡æ?author:
  link: http://dianacody.github.io/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#è¯„è®ºä¿¡æ¯
disqus:
  config: true
  id: dianacodyblog

duoshuo:
  config: false
  id: dianacody