# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Jekyll Theme
description: Just another Jekyll theme design and code by zhanxin.info.
keywords: Jekyll Theme
url: http://dianacody.github.io
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: é¦–é¡µ
    url: /index.html
  - text: åˆ†ç±»ç›®å½• 
    url: /categories.html
  - text: æ–‡ç« å½’æ¡£
    url: /archives.html
  - text: è”ç³»æˆ?
    url: /contact.html
  - text: å‹æƒ…é“¾æ¥
    url: /links.html

#Author config
author:
    name: æŒå¿ƒ
    email: dianacodyleaf@gmail.com
    imageLink: http://tp2.sinaimg.cn/1832671293/180/40020872447/1
    simpleIntro: æˆ‘æ˜¯ã€Œå±•æ–°å±•æ–°ã€ï¼Œä¸€ä¸ªçŸ›ç›¾ä½“çš„åŒ–èº«ï¼Œåœ¨ä½ çš„æŒå¿ƒé‡Œã€?
    detailIntro:
      <p>Jekyll æ˜¯ä¸€ä¸ªç®€æ´çš„ã€ç‰¹åˆ«é’ˆå¯¹åšå®¢å¹³å°çš„ é™æ€ç½‘ç«?ç”Ÿæˆå™¨ã€‚å®ƒä½¿ç”¨ä¸€ä¸ªæ¨¡æ¿ç›®å½•ä½œä¸ºç½‘ç«™å¸ƒå±€çš„åŸºç¡€æ¡†æ¶ï¼Œå¹¶åœ¨å…¶ä¸Šè¿è¡?Textile ã€?Markdown æˆ?Liquid æ ‡è®°è¯­è¨€çš„è½¬æ¢å™¨ï¼Œæœ€ç»ˆç”Ÿæˆä¸€ä¸ªå®Œæ•´çš„é™æ€Webç«™ç‚¹ï¼Œå¯ä»¥è¢«æ”¾ç½®åœ¨Apacheæˆ–è€…ä½ å–œæ¬¢çš„å…¶ä»–ä»»ä½•WebæœåŠ¡å™¨ä¸Šã€‚å®ƒåŒæ—¶ä¹Ÿæ˜¯ GitHub Pages ã€ä¸€ä¸ªç”± GitHub æä¾›çš„ç”¨äºæ‰˜ç®¡é¡¹ç›®ä¸»é¡µæˆ–åšå®¢çš„æœåŠ¡ï¼Œåœ¨åå°æ‰€è¿è¡Œçš„å¼•æ“ã€?/p>
      <p>å¾ˆæ—©ä¹‹å‰ï¼Œä½¿ç”¨è¿‡ wordpress æ¥å†™åšå®¢ã€‚ä½†æ˜¯è¿˜è¦å¤„ç†å¾ˆå¤šçš„åº•å±‚é—®é¢˜ã€‚è€Œä½¿ç”?Jekyll æ¥å†™åšå®¢ï¼Œå¯ä»¥å¾ˆç®€å•ï¼Œå†?Markdown å°±å¥½ã€‚ç„¶è€Œï¼ŒJekyll è¿˜å¾ˆå¹´è½»ï¼Œæ²¡æœ‰å¾ˆå¤šä¸»é¢˜çš„æ”¯æŒã€‚è¿™é‡Œçš„ä¸»é¢˜ï¼Œå°±æ˜¯ä¸º Jekyll è€Œå†™çš„ã€‚å¸Œæœ›ä½ èƒ½å–œæ¬¢ã€?/p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/pizn
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/dianacody
  - class: icon-twitter
    url: http://twitter.com/
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: æŒå¿ƒ
      url: http://dianacody.github.io
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://dianacody.github.io/themes.html
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: å…¶ä»–ç›¸å…³é“¾æ¥

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: dianacodyblog

duoshuo:
  config: true
  id: dianacody