# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

#ç«™ç‚¹åŸºç¡€é…ç½®
title: iLotus
subTitle: Just another Jekyll blog.
description: è¿™æ˜¯ PIZn çš„åˆä¸€ä¸ªåšå®¢ï¼Œå®ƒæ˜¯åŸºäº Jekyll æ­å»ºèµ·æ¥çš„ã€‚åœ¨è¿™é‡Œï¼Œä¸ä»…ä»…æ˜¯ç”¨æ¥å¿«é€Ÿè®°å½•å·¥ä½œï¼Œå­¦ä¹ ï¼Œç”Ÿæ´»çš„ä¸€ç‚¹ä¸€æ»´çš„åœ°æ–¹ï¼Œæ›´æ˜?PIZn å¯?Jekyll çš„å­¦ä¹ å’Œä½¿ç”¨çš„ä¸€æ¬¡æœ‰æ„ä¹‰çš„å®è·µã€?
url: http://dianacody.github.io
feed: /atom.xml

#èœå•é…ç½®
nav:
  - text: é¦–é¡µ
    url: /index.html
    icon: icon-home
    class: home
  - text: æ–‡ç« å½’æ¡£
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: å…³äºæˆ?    url: /contact.html
    icon: icon-envelope-alt
    class: none
  - text: è”ç³»æˆ?    url: http://dianacody.github.io/contact.html
    icon: icon-heart
    class: none
  - text: åšå®¢æºä»£ç ?    url: https://github.com/dianacdy/dianacody.github.io
    icon: icon-github
    class: none

page:
  - text: æ–‡ç« åˆ†ç±»
    url: /archives.html
    last: true
  - text: å‹æƒ…é“¾æ¥
    url: /links.html
    last: true
  - text: å…³äºæˆ?    url: /contact.html
    last: false

author:
  name: DianaCody
